export const serviceCategories = {
    "categories": [
        "Automobiles - Cleaning",
        "Automobiles - Repair",
        "Automobiles - Towing",
        "Babysitting / Child Care",
        "Chauffeur / Ride Share",
        "Cleaning - Misc",
        "Computers - Misc",
        "Computers - Repair",
        "Computers - Web Programming",
        "Cooking",
        "Elder Care",
        "Errands",
        "Handyman - Misc",
        "Handyman - Appliance Repair",
        "Handyman - Carpentry",
        "Handyman - Electrical",
        "Handyman - Locksmithing",
        "Handyman - Painting",
        "Miscellaneous / Other / Unlisted",
        "Pet - Care / Sitting",
        "Plumbing - Misc",
        "Tax Preparation",
        "Teaching / Tutoring - Cooking",
        "Teaching / Tutoring - Fitness",
        "Teaching / Tutoring - Misc",
        "Teaching / Tutoring - Math",
        "Teaching / Tutoring - Music",
        "Teaching / Tutoring - Science",
        "Teaching / Tutoring - Computer Programming",
        "Yard - Landscaping",
        "Yard - Misc",
        "Yard - Fencing",
        "Yard - Mowing / Trimming",
        "Yard - Sprinklers",
    ]
}