export const serviceCategories = {
    "categories": [
        "Babysitting - Child Care",
        "Cleaning - Misc",
        "Computers - Misc",
        "Computers - Repair",
        "Computers - Web Programming",
        "Handyman - Misc",
        "Handyman - Appliance Repair",
        "Handyman - Carpentry",
        "Handyman - Electrical",
        "Handyman - Locksmithing",
        "Handyman - Painting",
        "Pet - Care, Sitting",
        "Plumbing - Misc",
        "Tax Preparation",
        "Teaching / Tutoring - Cooking",
        "Teaching / Tutoring - Misc",
        "Teaching / Tutoring - Math",
        "Teaching / Tutoring - Science",
        "Teaching / Tutoring - Computer Programming",
        "Towing",
        "Yard - Landscaping",
        "Yard - Misc",
        "Yard - Fencing",
        "Yard - Mowing, Trimming",
        "Yard - Sprinklers",
    ]
}